
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "hitechnic-gyro.h"

float initial; 	//initial gyro reading
float heading; 	//robots current yaw
float radheading;   //heading in radians
int lastTime = 0;	//last time header was updated, used to find average change in rotation
float FLset; //front-left set, refers to Front-Left and Back-Right
float FRset; //front-right set, refers to Front-Right and Back-Left motor
float joyAngle; // angle of the first joystick
float currHeading;
float sonarValue;
float delTime = 0;//calibration
float prevHeading = 0;
float curRate = 0;
int deadZone = 15;
float calibrate = 0;

void initializeRobot()
{
	//   accelStart(S4);//accel

	initial = 0;
	for(int i = 0; i < 100; i++){//Sensor
		initial += SensorValue[S4];
		wait10Msec(1);
	}
	initial = initial / 100;//Sensor

	servo[scoreLeft]=35;
	servo[scoreRight]=220;

	servo[rollingBack1] = 0;
	servo[rollingBack2] = 0;
	servo[rollingSide] = 50; //rolling goal clamps are down
	servo[autonomousArm] = 195;
	return;
}

void motorTrigger(tMotor motorCall,int x,int y,int z)
{
	motor[motorCall]= (y+x+z);
}

void move(int angle, int power, int time)
{

	int x = power*128/100*cosDegrees(angle);
	int y = power*128/100*sinDegrees(angle);
	int z = 0;

//	int accelValue = SensorValue(Accel); //set accelerometer value to accelValue
	int gyroValue = SensorValue(Gyro); //set gyroscope value to gyroValue

	nxtDisplayCenteredBigTextLine(5,"%d",gyroValue); //display gyroValue to NXT
	//nxtDisplayCenteredBigTextLine(5,"%d",accelValue); //display accelValue to NXT

	int trueX = (cosDegrees(currHeading+calibrate)*x)-(sinDegrees(currHeading+calibrate)*y); //sets trueX to rotated x value
	int trueY = (sinDegrees(currHeading+calibrate)*x)+(cosDegrees(currHeading+calibrate)*y); //sets trueY to rotated y value

	x = trueX;
	y = trueY;

	motorTrigger(frontRight,x,-y,-z);
	motorTrigger(backRight,-x,-y,-z);
	motorTrigger(frontLeft,x,y,-z);
	motorTrigger(backLeft,-x,y,-z);

	wait1Msec(time);

	motorTrigger(frontRight,0,0,0);
	motorTrigger(backRight,0,0,0);
	motorTrigger(frontLeft,0,0,0);
	motorTrigger(backLeft,0,0,0);

	wait1Msec(100);

}

void rotate(int relativeAngle, int direction, int power)
{
	int finalHeading = currHeading + direction*relativeAngle;

	if (finalHeading > 360) finalHeading -= 360;
	else if(finalHeading < 0) finalHeading += 360;

	while(abs(finalHeading - currHeading) != 0)
	{
		int x = 0;
		int y = 0;
		int z = power*direction*128/100;

		motorTrigger(frontRight,x,-y,-z);
		motorTrigger(backRight,-x,-y,-z);
		motorTrigger(frontLeft,x,y,-z);
		motorTrigger(backLeft,-x,y,-z);
	}
	motorTrigger(frontRight,0,0,0);
	motorTrigger(backRight,0,0,0);
	motorTrigger(frontLeft,0,0,0);
	motorTrigger(backLeft,0,0,0);

	wait1Msec(100);
}

void releaseSide(bool release)
{
	if (release)servo[rollingSide] = 200; //release
	else servo[rollingSide] = 50; //clamp
	wait1Msec(100);
}

void releaseBack(bool release)
{
	if (release)//release
	{
		servo[rollingBack1] = 150;
		servo[rollingBack2] = 150;
	}
	else //clamp
	{
		servo[rollingBack1] = 0;
		servo[rollingBack2] = 0;
	}
	wait1Msec(100);
}

void scoreAutonomous()
{
	servo[autonomousArm] = 100;
	wait1Msec(1000);
	servo[autonomousArm] = 195;
	wait1Msec(100);
}

task getHeading() {
	HTGYROstartCal(Gyro);
	PlaySound(soundBeepBeep);
	while (true) {
		time1[T1] = 0;
		curRate = HTGYROreadRot(Gyro);
		if (abs(curRate) > 3) //sets deadzones for gyroscope
		{
			prevHeading = currHeading;
			currHeading = prevHeading + curRate * delTime; //changes current heading based on the rate of change and time elapsed
			if (currHeading > 360) currHeading -= 360; //keeps current heading between 0 and 360
			else if (currHeading < 0) currHeading += 360; // keeps curent heading between 0 and 360
		}
		wait1Msec(5);
		delTime = ((float)time1[T1]) / 1000;

	}
}

task   getXY()
{  //365.76

}//18in = 45.72

task display()
{
	while (true){
		eraseDisplay();
		nxtDisplayCenteredTextLine(0, "Heading: %d", currHeading);
		nxtDisplayCenteredTextLine(1, "joyAngle: %d", joyAngle);
		nxtDisplayCenteredTextLine(2, "Sonar: %d", sonarValue);
		wait1Msec(20);
	}
}

task getAccel()
{
	int X_Accel;
	int Y_Accel;

	//X_Accel = SensorValue[xAxis]/2000;
	//Y_Accel = SensorValue[yAxis];

}

task calibrateDrive()//needs work, doing some wack stuff
{
			calibrate = 360 - currHeading;
			PlaySound(soundUpwardTones);
			wait1Msec(500);
			/*

			initializeRobot();
			HTGYROstartCal(Gyro);
			delTime = 0;//calibration
			prevHeading = 0;
			curRate = 0;
			wait1Msec(500);
			*/

}

/*
task main()
{
	initializeRobot();
	waitForStart();
	/*
	motorTrigger(frontright,0,-30,-0);
	motorTrigger(backright,-0,-30,-0);
	motorTrigger(frontleft,0,30,-0);
	motorTrigger(backleft,-0,30,-0);
	wait1Msec(1750);
	motor[backleft] = 0;
	motor[frontright] = 0;
	motor[backright] = 0;
	motor[frontleft] = 0;
	motor[frontright]=30;
	motor[frontleft]=-30;
	motor[backleft]=-30;
	motor[backright]=-30;
	wait1Msec(1000);
  */
	//motor[transportA]=0;
	//motor[transportB]=0; //stop linear slides
	//drive into parking zone
	while(true)
	{
		//move(int angle, int power, int time) - power(0-100), time(millisec)
		//rotate(int relativeAngle, int direction, int power)
		//direction: -1 --> cw, 1 --> ccw, power(0-100)
		StartTask(getHeading);
		nxtDisplayBigTextLine(3, "IR:%d", SensorValue(light));
		move(270,70,500);
		rotate(90,-1,50);
		move(270,70,500);
		releaseSide(true);
		releaseSide(false);
		releaseBack(true);
		releaseBack(false);
		scoreAutonomous();
		wait1Msec(500000);
	}
}
*/
