#pragma config(Sensor, S1,     accel,          sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Robotics (PROGRAMENG)/hitechnic-accelerometer.h";

int accelX,accelY,accelZ=0;
string accelTmp;

task main()
{
while(HTACreadAllAxes(accel,accelX,accelY,accelZ)){}
}
