#pragma config(Sensor, S1,     infraredUno,    sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S2,     infraredDos,     sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float irUno;
float irDos, irSighted=0;
float timeTaken = 0;
float x = 0;
float irPrev[] = {0,0};

task getIr() {

		irUno = SensorValue(infraredUno);
		irDos = SensorValue(infraredDos);

		while(irSighted==0){

		irUno = SensorValue(infraredUno);
		irDos = SensorValue(infraredDos);
		if(irUno==7 && irDos==3){irSighted=1;}
		else if(irUno==3 && irDos==7){irSighted=1;}
		irPrev[0] = irUno;
		irPrev[1] = irDos;
		}
		x = 1;
		time1[T1]=0;

		while(irSighted==1){
			x=2;
			irUno = SensorValue(infraredUno);
			irDos = SensorValue(infraredDos);
			if(irUno!=irPrev[0] || irDos!=irPrev[1]){irSighted=0;}
		}

		x=3;
		timeTaken = ((float)time1[T1])/2.0;
		x=4;

		while(true){
			nxtDisplayBigTextLine(0,"%d",irUno);
			nxtDisplayBigTextLine(2,"%d",irDos);
			nxtDisplayBigTextLine(4,"%d",irSighted);
		}

}

task main() {
	//turn here
	motor[frontright]=-50;
	motor[frontleft]=-50;
	motor[backright]=-50;
	motor[backleft]=-50;
	StartTask(getIr);
	while(timeTaken==0){
	}
	time1[T1]=0;
	motor[frontright]=50;
	motor[frontleft]=50;
	motor[backright]=50;
	motor[backleft]=50;
	while(time1[T1]!=timeTaken){
	}
	motor[frontright]=0;
	motor[frontleft]=0;
	motor[backright]=0;
	motor[backleft]=0;
}
