#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S3,     HTSPB,          sensorI2CCustom9V)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift2,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     backLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     collector2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    rollingGoalLeft,      tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    rollingGoalRight,     tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Includes
#include "Robotics (PROGRAMENG)/hitechnic-superpro.h"
#include "JoystickDriver.c"
#include "Robotics (PROGRAMENG)/hitechnic-gyro.h"
#include "Collector.c"
#include "RollingGoal.c"
#include "Dump.c"
#include "Robotics (PROGRAMENG)/hitechnic-sensormux.h"
#include "Robotics (PROGRAMENG)/hitechnic-accelerometer.h"
#include "encoderFunctions.c"
#include "ProtoBoardLogic.c"
#include "driveFunctions.c"
#include "liftFunctions.c"
#include "joyFunctions.c"

float buttonA = 0, buttonB = 0;
bool safety;

task joyButtons(){
float liftVal = nMotorEncoder(motorLift2);
while(true)
	{
		nxtDisplayBigTextLine(0,"%d",nMotorEncoder[motorLift2]);
		getJoystickSettings(joystick);
		if(joy1Btn(7))
		{
			PlaySound(soundFastUpwardTones);
			calibrate = 360 - currHeading;
			wait1Msec(500);
		}

		if(joy2Btn(4))
			{
			stopTask(Lift);
			motor[motorLift2]=-90;
			motor[motorLift1]=-90;
			nMotorEncoder[motorLift2] = 0;
			wait1Msec(50);
			while(abs(nMotorEncoder[motorLift2])<(1440*2.5)
			{
			}
			motor[motorLift2]=0;
			motor[motorLift1]=0;
			startTask(Lift);
		}

		if(joy2Btn(2)){
			buttonA++;
			if(buttonA % 2 == 1 && !safety){
				stopTask(Lift);
				motor[motorLift2]=-90;
				motor[motorLift1]=-90;
				wait1Msec(50);
				safety = true;
				while(abs(nMotorEncoder[motorLift2])<(1440 * 1.55))
				{
				}
				stopEncodedMotors();
				score = (score + 1)%2;
				startTask(Lift);
				nMotorEncoder[motorLift2] = 0;
				safety = false;
			}
			else if(buttonA % 2 == 0 && !safety){
				stopTask(Lift);
				score = (score + 1)%2;
				motor[motorLift2]=90;
				motor[motorLift1]=90;
				wait1Msec(50);
				safety = true;
				while(abs(nMotorEncoder[motorLift2])<(1440*1.55))
				{
				}
				stopEncodedMotors();
				startTask(Lift);
				nMotorEncoder[motorLift2] = 0;
				safety = false;
			}
		}

		if(joy2Btn(3))
			{
			buttonB++;
			if(buttonB % 2 == 1 && !safety){
				stopTask(Lift);
				motor[motorLift2]=-90;
				motor[motorLift1]=-90;
				wait1Msec(50);
				safety = true;
				while(abs(nMotorEncoder[motorLift2])<(1440*2.4 ))
				{
				}
				stopEncodedMotors();
				score = (score + 1)%2;
				startTask(Lift);
				nMotorEncoder[motorLift2] = 0;
				safety = false;
			}
			else if(buttonB % 2 == 0 && !safety){
				stopTask(Lift);
				score = (score + 1)%2;
				motor[motorLift2]=90;
				motor[motorLift1]=90;
				wait1Msec(50);
				safety = true;
				while(abs(nMotorEncoder[motorLift2])<(1440*2.4))
				{
				}
				stopEncodedMotors();
				startTask(Lift);
				nMotorEncoder[motorLift2] = 0;
				safety = false;
			}

		}
	}
}
