#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S3,     HTSPB,          sensorI2CCustom9V)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorLift1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLift2,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     backLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     collector2,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    dump,                 tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    rollingGoalLeft,      tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    rollingGoalRight,     tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Includes
//#include "Robotics (PROGRAMENG)/hitechnic-superpro.h"
#include "JoystickDriver.c"
#include "hitechnic-gyro.h"
#include "Collector.c"
#include "RollingGoal.c"
#include "Dump.c"
#include "hitechnic-sensormux.h"
#include "encoderFunctions.c"
#include "ProtoBoardLogic.c"
#include "driveFunctions.c"
#include "liftFunctions.c"
#include "joyFunctions.c"
//#include "TurnRotate.c"
//#include "Lift.c"
//#include "Testing.c"
//

//SMUX Sensors
//const tMUXSensor Accel = msensor_S4_2;
//const tMUXSensor UltraSonic = msensor_S4_3;
//

//Global Variables
int deadZone = 15;
float slideBtn = 0;
float clampPress = 0;
float globalZ;
float trueZ;

int _x_axis, _y_axis, _z_axis, pitch, tiltCount = 0;
float totalAccel = 0;
//



task main()
{
	initializeRobot();
	StartTask(getHeading);
	StartTask(FPSDrive);
	StartTask(runCollector);
	StartTask(runRollingGoal);
	StartTask(runDump);
	StartTask(Lift);
	startTask(limitSwitch);
	//StartTask(getAccel);
	//startTask(encoderMove);
	//StartTask(runTurnRotate);
	//StartTask(wheeleySuppresor);
	waitForStart();
	startTask(joyButtons);
	while(true)
	{
		//security measures
	}
	while(true)
	{
		wait1Msec(2000);
	}
}
