#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontright,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backright,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontleft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     backleft,      tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"

float x;
float y;
float onefour;
float twothree;
int power;


void initializeRobot()
{
	return;
}

task main()
{


	initializeRobot();

	waitForStart();

	while(true)
	{
		getJoystickSettings(joystick);

		if(abs(joystick.joy1_x1)>15)
			x = joystick.joy1_x1;
		else
			x=0;
		if(abs(joystick.joy1_y1)>15)
			y = joystick.joy1_y1;
		else
			y=0;

		onefour= -atan (y/x);
		twothree= -atan (y/x + PI);

		if(abs(joystick.joy1_y2)>15)
			int y2=joystick.joy1_y2;
		else
			y2=0;
		if(abs(joystick.joy1_x2)>15)
			int x2=joystick.joy1_x2;
		else
			x2=0;

		if(y2>0)
		{
			int power=y2;
		}
		else
		{
			int power=-y2;
		}

		if(x != 0)
		{
			motor[frontright]= -power*sin(onefour);
			motor[backright]= -power*cos(onefour);
			motor[frontleft]= power*cos(twothree);
			motor[backleft]= power*sin(twothree);
		}
		else
		{
			motor[frontright]=0;
			motor[backright]=0;
			motor[frontleft]=0;
			motor[backleft]=0;
		}
		if(x == 0)
		{
			motor[frontright]=power;
			motor[backright]=power;
			motor[frontleft]=-power;
			motor[backleft]=-power;
		}

	}

}
