#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorB,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorC,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//take initial reading
	int initial = SensorValue[gyro]; //the initial sensor value of the gyro
	int degreesWanted = 90; //how many degrees i want to turn
	int gyroReading = SensorValue[gyro]- initial; //final-intial
	int degreesTurned = gyroReading*.01;
	/*d=rt, unit of gyroReading (r) is degrees/time * time,
	eliminates time, so degreesTurned (d) is in degrees*/

	//start turning
	motor[motorB] = 15;
	motor[motorC] = -15;

	//check if turned enough
	while(degreesTurned<degreesWanted)
	{
		wait1Msec(10); //continue tuning for .01 sec, then read again
	}

	//stop turning
	motor[motorB] = 0;//when degreesTurned=degreesWanted, stop
	motor[motorC] = 0;



}
