#pragma config(Sensor, S1,     proto,          sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:\Program Files\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-superpro.h"

task main()
{

HTSPBwriteIO(S1, 0);

}
