#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
task main()
{
	getJoystickSettings(joystick);
	while(true)
	{
		if(abs(joystick.joy1_y2)<50)
			joystick.joy1_y1=0;
		if(abs(joystick.joy1_y1)<50)
			joystick.joy1_y1=0;
		motor[left]=-joystick.joy1_y1;
		motor[right]=joystick.joy1_y2;


	}
}
