#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Sensor, S4,     Gyro,           sensorHiTechnicIRSeeker600)
#pragma config(Motor,  mtr_S1_C1_1,     backRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     emptyMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     liftRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     liftLeft,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    rollingSide,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    rollingBack1,         tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    scoreRight,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    scoreLeft,            BadType)
#pragma config(Servo,  srvo_S2_C1_5,    rollingBack2,         tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    autonomousArm,        tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "hitechnic-gyro.h"

float initial;	//initial gyro reading
float heading;	//robots current yaw
float radheading;		//heading in radians
int lastTime = 0;	//last time header was updated, used to find average change in rotation
float FLset; //front-left set, refers to Front-Left and Back-Right
float FRset; //front-right set, refers to Front-Right and Back-Left motor
float joyAngle; // angle of the first joystick
float currHeading;
float sonarValue;
float delTime = 0;//calibration
float prevHeading = 0;
float curRate = 0;
int deadZone = 15;
float calibrate = 0;
float sonarOne;
float lightVal;
float stepCounter = 0;
int upPin;
int downPin;
int resetPin;
bool planDecider = true;
int debugTool = 0;
float encoderDir = 0;
float corrDir = 0;
float oldfr = 0;
float oldfl = 0;
float oldbl = 0;
float oldbr = 0;

void initializeRobot()
{
	//	 accelStart(S4);//accel

	initial = 0;
	for(int i = 0; i < 100; i++){//Sensor
		initial += SensorValue[S4];
		wait10Msec(1);
	}
	initial = initial / 100;//Sensor

	servo[scoreLeft]=35;
	servo[scoreRight]=220;

	servo[rollingBack1] = 0;
	servo[rollingBack2] = 0;
	servo[rollingSide] = 50; //rolling goal clamps are down
	servo[autonomousArm] = 195;
	return;
}

void motorTrigger(tMotor motorCall,int x,int y,int z)
{
	motor[motorCall]= (y+x+z);
}

void stopMotors()
{
	motor[backleft] = 0;
	motor[frontright] = 0;
	motor[backright] = 0;
	motor[frontleft] = 0;
}

void move(int angle, int power, float time)
{

	int x = power*128/100*cosDegrees(angle);
	int y = power*128/100*sinDegrees(angle);
	int z = 0;

	//	int accelValue = SensorValue(Accel); //set accelerometer value to accelValue
	int gyroValue = SensorValue(Gyro); //set gyroscope value to gyroValue

	nxtDisplayCenteredBigTextLine(5,"%d",gyroValue); //display gyroValue to NXT
	//nxtDisplayCenteredBigTextLine(5,"%d",accelValue); //display accelValue to NXT

	int trueX = (cosDegrees(currHeading+calibrate)*x)-(sinDegrees(currHeading+calibrate)*y); //sets trueX to rotated x value
	int trueY = (sinDegrees(currHeading+calibrate)*x)+(cosDegrees(currHeading+calibrate)*y); //sets trueY to rotated y value

	x = trueX;
	y = trueY;

	motorTrigger(frontRight,x,-y,-z);
	motorTrigger(backRight,-x,-y,-z);
	motorTrigger(frontLeft,x,y,-z);
	motorTrigger(backLeft,-x,y,-z);

	wait1Msec(time);

	motorTrigger(frontRight,0,0,0);
	motorTrigger(backRight,0,0,0);
	motorTrigger(frontLeft,0,0,0);
	motorTrigger(backLeft,0,0,0);

	wait1Msec(100);

}

void rotate(int relativeAngle, int direction, int power)
{
	int finalHeading = currHeading + direction*relativeAngle;

	if (finalHeading > 360) finalHeading -= 360;
	else if(finalHeading < 0) finalHeading += 360;

	while(abs(finalHeading - currHeading) > 1)
	{
		int x = 0;
		int y = 0;
		int z = power*direction*128/100;

		motorTrigger(frontRight,x,-y,-z);
		motorTrigger(backRight,-x,-y,-z);
		motorTrigger(frontLeft,x,y,-z);
		motorTrigger(backLeft,-x,y,-z);
	}
	motorTrigger(frontRight,0,0,0);
	motorTrigger(backRight,0,0,0);
	motorTrigger(frontLeft,0,0,0);
	motorTrigger(backLeft,0,0,0);

	wait1Msec(100);
}

void releaseSide(bool release)
{
	if (release)servo[rollingSide] = 200; //release
	else servo[rollingSide] = 50; //clamp
		wait1Msec(100);
}

void releaseBack(bool release)
{
	if (release)//release
	{
		servo[rollingBack1] = 150;
		servo[rollingBack2] = 150;
	}
	else //clamp
	{
		servo[rollingBack1] = 0;
		servo[rollingBack2] = 0;
	}
	wait1Msec(100);
}

void scoreAutonomous()
{
	servo[autonomousArm] = 100;
	wait1Msec(1000);
	servo[autonomousArm] = 195;
	wait1Msec(100);
}

task getHeading() {
	lightVal = SensorValue(Gyro);
	sonarOne= SensorValue(sonar);
	HTGYROstartCal(Gyro);
	PlaySound(soundBeepBeep);
	while (true) {
		time1[T1] = 0;
		curRate = HTGYROreadRot(Gyro);
		if (abs(curRate) > 3) //sets deadzones for gyroscope
		{
			prevHeading = currHeading;
			currHeading = prevHeading + curRate * delTime; //changes current heading based on the rate of change and time elapsed
			if (currHeading > 360) currHeading -= 360; //keeps current heading between 0 and 360
			else if (currHeading < 0) currHeading += 360; // keeps curent heading between 0 and 360
		}
		wait1Msec(5);
		delTime = ((float)time1[T1]) / 1000;

	}
}

task	 getXY()
{	 //365.76

}//18in = 45.72

task display()
{
	while (true){
		eraseDisplay();
		nxtDisplayCenteredTextLine(0, "Heading: %d", currHeading);
		nxtDisplayCenteredTextLine(1, "joyAngle: %d", joyAngle);
		nxtDisplayCenteredTextLine(2, "Sonar: %d", sonarValue);
		wait1Msec(20);
	}
}

task getAccel()
{
	int X_Accel;
	int Y_Accel;

	//X_Accel = SensorValue[xAxis]/2000;
	//Y_Accel = SensorValue[yAxis];

}
void moveRight(float s) {
	motorTrigger(frontright, 0, 50, 0);
	motorTrigger(backright, 0, -50, 0);
	motorTrigger(frontleft, 0, 50, 0);
	motorTrigger(backleft, 0, -50, 0);
	wait1MSec(s*1000);
}

void moveForward(float s) {
	motorTrigger(frontright,0,-50,-0);
	motorTrigger(backright,-0,-50,-0);
	motorTrigger(frontleft,0,50,-0);
	motorTrigger(backleft,-0,50,-0);
	wait1MSec(s*1000);
}

task autoAlign()//ghost tracking
{
	while(true)
	{
		if(currHeading >= 3 && currHeading <180) // currHeading <= 355
		{
			motorTrigger(frontright,0,0,20);
			motorTrigger(backright,0,0,20);
			motorTrigger(frontleft,0,0,20);
			motorTrigger(backleft,0,0,20);
			//PlaySound(soundBlip);
			//PlaySound(soundUpwardTones);

			//wait1Msec(100);
		}
		else if(currHeading <=355 && currHeading >= 180)
		{
			//PlaySound(soundDownwardTones);
			motorTrigger(frontright,0,0,-20);
			motorTrigger(backright,0,0,-20);
			motorTrigger(frontleft,0,0,-20);
			motorTrigger(backleft,0,0,-20);
		}
		else
		{
			//stopMotors();
			//PlaySound(soundBeepBeep);
		}
 }
}

void singleAlign()
{
 alignmentLoop:	while(true)
	{
		if(currHeading >= 5 && currHeading <180) // currHeading <= 355
		{
			motorTrigger(frontright,0,0,20);
			motorTrigger(backright,0,0,20);
			motorTrigger(frontleft,0,0,20);
			motorTrigger(backleft,0,0,20);
			//PlaySound(soundBlip);
			//PlaySound(soundUpwardTones);

			//wait1Msec(100);
		}
		else if(currHeading <=355 && currHeading >= 180)
		{
			//PlaySound(soundDownwardTones);
			motorTrigger(frontright,0,0,-20);
			motorTrigger(backright,0,0,-20);
			motorTrigger(frontleft,0,0,-20);
			motorTrigger(backleft,0,0,-20);
		}
		else
		{
			alignmentLoop: break;
			//PlaySound(soundBeepBeep);
		}
 }
}



task calibrateDrive()//needs work, doing some wack stuff
{
	calibrate = 360 - currHeading;
	PlaySound(soundUpwardTones);
	wait1Msec(500);
	/*

	initializeRobot();
	HTGYROstartCal(Gyro);
	delTime = 0;//calibration
	prevHeading = 0;
	curRate = 0;
	wait1Msec(500);
	*/
}

task stopMotors() {
	motor[frontleft] = 0;
	motor[backleft] = 0;
	motor[backright] = 0;
	motor[frontright] = 0;
}

void waitSeconds(float x){
	wait1Msec(x*1000);
}

void moveCardinalDirection(char* direction){
	if(strncmp(direction, "east", 3)==0){
		motor[frontleft] = -50;
		motor[frontright] = -50;
		motor[backleft] = 50;
		motor[backright] = 50;
		encoderDir = -1;
	}
	else if(strncmp(direction, "west", 3)==0){
		motor[frontleft] = 50;
		motor[frontright] = 50;
		motor[backleft] = -50;
		motor[backright] = -50;
		encoderDir = -1;
	}
	else if(strncmp(direction, "north", 3)==0){
		motor[frontleft] = 50;
		motor[frontright] = -50;
		motor[backleft] = 50;
		motor[backright] = -50;
		debugTool = 1;
		encoderDir = 1;
	}
	else if(strncmp(direction, "south", 3)==0){
		motor[frontleft] = -50;
		motor[frontright] = 50;
		motor[backleft] = -50;
		motor[backright] = 50;
		encoderDir = 1;
	}
	//strncmp(string1, string2, index) == 0)
}


void performStep()
{
	if(planDecider){//do plan a
		switch (stepCounter)
		{
			case 1:
		  	moveCardinalDirection("north");
			break;
			case 2:
				//more stuff
			break;
			case 3: break;
			case 4: break;
			case 5: break;
			case 6: break;
		}
	}
	else
	{
		switch (stepCounter)
		{
			case 1:
			//do stuff
			break;
			case 2: break;
			case 3: break;
			case 4: break;
			case 5: break;
			case 6: break;
		}
	}
}

task stepUpDown()
{
	if(upPin >= 500 && downPin >= 500)
	{
		planDecider = false;
    wait1Msec(1000);
		performStep();
  }//plan b
	else if (downPin >= 500)
	{
		stepCounter--;
		wait1Msec(1000);
		performStep();
	}
	else if(upPin >= 500)
	{
		stepCounter++;
		wait1Msec(1000);
		performStep();
	}
	else if(resetPin >= 500)
	{
			stepCounter = 0;
	}//reset
}

task align()
{
	oldfr = motor[frontright];
	oldfl = motor[frontleft];
	oldbl = motor[backleft];
	oldbr = motor[backright];
	while (currHeading != corrDir && abs(currHeading-corrDir)>5 )
	{

		motor[backleft] = oldbl;
		motor[backright] = oldbr;
		motor[frontright] = oldfr;
		motor[frontleft] = oldfl;
	}

}

task main()
{
	initializeRobot();
	StartTask(getHeading);
	StartTask(stepUpDown);
	StartTask(align);
	waitForStart();



	moveCardinalDirection("north"); //works
	corrDir	= 0;



	//MENG THIS MEANS YOU. DON'T MOVE THIS.
	while (true)
		{
			wait1Msec(2000); //REQUIRED, DO NOT MOVE
		}
}
