#pragma config(Sensor, S1,     sonar,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
float sonarOne;
task main()
{

while(true){

	sonarOne = SensorValue(sonar);

}

}
